[package]
name = "tiger-rs"
version = "0.1.0"
authors = ["Newton Ni <nwtnni@gmail.com>"]

[build-dependencies]
lalrpop = "0.15.2"

[dependencies]
failure = "0.1.1"
lalrpop-util = "0.15.2"
regex = "1.0.0"
structopt = "0.2"

[lib]
name = "tiger-rs"
path = "src/lib.rs"

[[bin]]
name = "tc"
path = "src/main.rs"
