[package]
name = "tiger-rs"
version = "0.1.0"
authors = ["Newton Ni <nwtnni@gmail.com>"]

[build-dependencies]
lalrpop = "0.15.2"

[dependencies]
codespan = "0.1.2"
lalrpop-util = "0.15.2"
regex = "1.0.0"
structopt = "0.2"

[[bin]]
name = "tc"
path = "src/main.rs"
